### ISSUE TITLE
bug: SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by wongjiahau** [rgoring/asciiquarium#1]
## Error
```
fish: 'asciiquarium' terminated by signal SIGSEGV (Address boundary error)
```

## Environment
```
fish, version 3.0.2
MacOS Big Sur, Version 11.2.3
MacBook Pro (15-inch, 2018)
```

**Comment by rgoring** [comment]
You're running this on a mac? Did you recompile the code, run it through an emulator, or something else? This code isn't supported for MacOS as far as I know.

**Comment by wongjiahau** [comment]
Yea I'm running it on Mac. I didn't recompile, I just installed it using 
```
brew install asciiquarium
```

**Comment by rgoring** [comment]
Ok. Interesting. Did it run at all or did you hit the segfault as soon as it started?

**Comment by wongjiahau** [comment]
I got this error as soon as it started.

**Comment by rgoring** [comment]
Ok - I see what's going on. This repository is for the Windows version of asciiquarium. On a mac, brew installs the Linux or Mac version hosted on https://robobunny.com/projects/asciiquarium/html/. There is no github repository for that. You might be able to contact the maintainer of the Linux version of asciiquarium through that webpage.

**Comment by rgoring** [comment]
Closing due to incorrect platform/version of asciiquarium.
