### ISSUE TITLE
How to install on windows?

### ISSUE THREAD

**Issue by dvpetta** [rgoring/asciiquarium#2]
Hey I think my kids will love this but I'm unsure how to install this on my windows 10 machine.  I have a two monitors connected to my laptop.  Thanks!

**Comment by rgoring** [comment]
You can download the latest 1.3 release (the zip file) from here: https://github.com/rgoring/asciiquarium/releases

Once you've got that, extract the .scr executable from the zip file and put it in a known location (Desktop, Documents, etc). Right click on the .scr file, and in Windows 10, there is option in the context menu to "Install". Click that, and it will be available in your Screen Saver settings in Windows 10.

**Comment by dvpetta** [comment]
Great, thanks @rgoring !
